### ISSUE TITLE
可以移植到stm32f103精英版吗，正点原子和rt论坛找了半天都找不到例程。

### ISSUE THREAD

**Issue by SpinLeo** [AngryBeast/rtthread_DHT11#1]

**Comment by AngryBeast** [comment]
可以的，你可以使用RT Thread Studio 编程，通过安装软件包的方式可以快速的改历程直接使用，如果用移植的方式，在F1已经能运行RTT的前提下复制过去应该差不多能用了。刚使用RTT的话推荐使用RT Thread Studio,可以方便的学习和使用
